/**
 * Static Export Initialization
 * 
 * Registers the static export handler for local development.
 * This enables the "Build and download static site" button to work locally.
 */

import { setStaticExportHandler } from "@webstudio-is/trpc-interface/index.server";
import { generateStaticExport } from "./static-export.server";
import env from "~/env/env.server";

// Extract the name from the domain.publish response
// The name is generated by domain.ts as `${project.id}-${nanoid()}.zip`
let pendingExportName: string | null = null;

/**
 * Set the expected export name before calling publish
 * This is called from the domain router before delegating to deployment
 */
export const setPendingExportName = (name: string) => {
  pendingExportName = name;
};

/**
 * Initialize the static export handler
 * This should be called once when the builder app starts
 */
export const initStaticExport = () => {
  setStaticExportHandler(async (input) => {
    // Only handle static exports
    if (input.destination !== "static") {
      return {
        success: false,
        error: "Handler only supports static exports",
      };
    }

    // Use exportName from input (passed by domain.ts), or fallback to pendingExportName, or buildId
    const exportName = input.exportName ?? pendingExportName ?? `${input.buildId}.zip`;
    pendingExportName = null; // Reset for next call

    console.log(`[Static Export] Starting export for build ${input.buildId}`);
    console.log(`[Static Export] Builder origin: ${input.builderOrigin}`);
    console.log(`[Static Export] Output file: ${exportName}`);

    // Get the service token for internal auth
    const serviceToken = env.TRPC_SERVER_API_TOKEN ?? "local-dev-token";

    // For local development, use localhost instead of the custom domain
    // to avoid SSL certificate issues with self-signed certs
    let builderOrigin = input.builderOrigin;
    if (builderOrigin.includes("wstd.dev") || builderOrigin.includes("localhost")) {
      // Use http://localhost:5173 for local dev to avoid SSL issues
      builderOrigin = "http://localhost:5173";
      console.log(`[Static Export] Using local origin: ${builderOrigin}`);
    }

    try {
      const result = await generateStaticExport({
        buildId: input.buildId,
        builderOrigin: builderOrigin,
        name: exportName,
        authToken: serviceToken,
      });

      if (result.success) {
        console.log(`[Static Export] Successfully generated: ${exportName}`);
      } else {
        console.error(`[Static Export] Failed: ${result.error}`);
      }

      return result;
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unknown error";
      console.error(`[Static Export] Error: ${message}`);
      return {
        success: false,
        error: message,
      };
    }
  });

  console.log("[Static Export] Handler registered for local development");
};
